{% set name = "neuralgcm" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/neuralgcm-{{ version }}.tar.gz
  sha256: fcef5bdd5537a2a758248625992ff00c7f094430d90f06f703e4cfad74503010

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - pip
  run:
    - python >=3.10
    - dinosaur-dycore
    - dm-haiku
    - gin-config
    - jax
    - jaxlib
    - numpy
    - optax
    - pandas
    - tensorflow-probability
    - xarray

test:
  imports:
    - neuralgcm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google-research/neuralgcm
  summary: Hybrid ML + physics model of the Earth's atmosphere
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
