{% set python_min = "3.10" %}
{% set name = "neuralgcm" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/neuralgcm-{{ version }}.tar.gz
  sha256: 24edbbb5d21e2d17a7475738f84602885eb011af3a23c33df293b2c5d10ac11c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - dinosaur-dycore  # dinosaur on PyPI
    - dm-haiku
    - gin-config
    - jax
    - jaxlib
    - numpy
    - optax
    - pandas
    - tensorflow-probability
    - xarray

test:
  imports:
    - neuralgcm
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/google-research/neuralgcm
  summary: Hybrid ML + physics model of the Earth's atmosphere
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
