{% set name = "neuralgcm" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/neuralgcm-{{ version }}.tar.gz
  sha256: e75889894e8948211cec9bf18c89df5e223ef5a6d9a6444bb42f4b36143a5c27

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - pip
  run:
    - python >=3.10
    - dinosaur-dycore
    - dm-haiku
    - gin-config
    - jax
    - jaxlib
    - numpy
    - optax
    - pandas
    - tensorflow-probability
    - xarray

test:
  imports:
    - neuralgcm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google-research/neuralgcm
  summary: Hybrid ML + physics model of the Earth's atmosphere
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
